"""add remaining tables

Revision ID: 16b1ae5f2c3e
Revises: b735cf4296c2
Create Date: 2026-07-07 10:15:08.989430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b1ae5f2c3e'
down_revision: Union[str, None] = 'b735cf4296c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
