"""init: create users, detection_records, training_tasks 
tables

Revision ID: b735cf4296c2
Revises: 6afae1be4574
Create Date: 2026-07-07 10:07:49.127484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b735cf4296c2'
down_revision: Union[str, None] = '6afae1be4574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
